function truncate(str, maxlength) {
    if (str.length > maxlength) {
        return str.slice(0, maxlength - 3) + '...'
        // итоговая длина равна maxlength
    }

    return str
}

function wrapTextUrls(text = '') {
    /**
     * Оборачивание всех найденных в тексте урлов и доменов в тег <a>
     * @author Simon Oganesyan
     * @param text
     * @param getting_title
     */
    /*eslint-disable */
	function wrapTextPartUrls(text_part) {
        console.log(text_part);
        if(text_part.includes('<a') && text_part.includes('</a>')) return text_part
        return text_part.replace(
			/(\b|^|\/\/|(\s|"|')(?=[а-яё]))(([-\w\.]{2,}@)(?!(https?|ftp|\/\/)))?((https?:|ftp:)\/\/[-а-яё\w+&@#\/%?=~_|!:,.;]{2,2048}|(https?:|ftp:)?(\/\/)?(www\.)?([-а-яё\w]{2,}\.){1,}(RU|RU\.COM|RU\.NET|COM\.RU|NET\.RU|ORG\.RU|PP\.RU|РФ|РУС|SU|MOSCOW|МОСКВА|MSK\.RU|MSK\.SU|SPB\.RU|SPB\.SU|TATAR|COM\.UA|KIEV\.UA|CO\.UA|BIZ\.UA|PP\.UA|AM|CO\.AM|COM\.AM|NET\.AM|ORG\.AM|RADIO\.AM|ARMENIA\.SU|GEORGIA\.SU|KZ|COM\.KZ|ORG\.KZ|AKTYUBINSK\.SU|CHIMKENT\.SU|EAST-KAZAKHSTAN\.SU|JAMBYL\.SU|KARAGANDA\.SU|KUSTANAI\.RU|KUSTANAI\.SU|MANGYSHLAK\.SU|NORTH-KAZAKHSTAN\.SU|TSELINOGRAD\.SU|MD|TJ|TM|ASHGABAD\.SU|ABKHAZIA\.SU|ADYGEYA\.RU|ADYGEYA\.SU|ARKHANGELSK\.SU|AZERBAIJAN\.SU|BALASHOV\.SU|BASHKIRIA\.RU|BASHKIRIA\.SU|BIR\.RU|BRYANSK\.SU|BUKHARA\.SU|BY|CBG\.RU|DAGESTAN\.RU|DAGESTAN\.SU|GROZNY\.RU|GROZNY\.SU|IVANOVO\.SU|KALMYKIA\.RU|KALMYKIA\.SU|KALUGA\.SU|KARACOL\.SU|KARELIA\.SU|KHAKASSIA\.SU|KRASNODAR\.SU|KURGAN\.SU|LENUG\.SU|MARINE\.RU|MORDOVIA\.RU|MORDOVIA\.SU|MURMANSK\.SU|MYTIS\.RU|NALCHIK\.RU|NALCHIK\.SU|NAVOI\.SU|NOV\.RU|NOV\.SU|OBNINSK\.SU|PENZA\.SU|POKROVSK\.SU|PYATIGORSK\.RU|SOCHI\.SU|TASHKENT\.SU|TERMEZ\.SU|TOGLIATTI\.SU|TROITSK\.SU|TULA\.SU|TUVA\.SU|VLADIKAVKAZ\.RU|VLADIKAVKAZ\.SU|VLADIMIR\.RU|VLADIMIR\.SU|VOLOGDA\.SU|БАЛАКЛАВА\.РФ|ДОНУЗЛАВ\.РФ|ЕВПАТОРИЯ\.РФ|ИНКЕРМАН\.РФ|КАЗАНТИП\.РФ|КОКТЕБЕЛЬ\.РФ|МАССАНДРА\.РФ|ОРЕАНДА\.РФ|СЕВАСТОПОЛЬ\.РФ|СИМФИ\.РФ|ТАРХАНКУТ\.РФ|ЯЛТА\.РФ|RU\.COM|SU|COM\.UA|KIEV\.UA|CO\.UA|BIZ\.UA|RADIO\.AM|KZ|COM\.KZ|ORG\.KZ|COM|NET|ORG|BIZ|TRAVEL|INFO|NAME|PW|ОРГ|COM|NET|ORG|NAME|PW|ДЕТИ|ОНЛАЙН|САЙТ|ACADEMY|ACCOUNTANT|ACCOUNTANTS|ACTOR|ADULT|AERO|AGENCY|AIRFORCE|APARTMENTS|ART|ASSOCIATES|ATTORNEY|AUCTION|AUDIO|AUTO|BABY|BAND|BAR|BARGAINS|BEER|BEST|BET|BID|BIKE|BINGO|BLACK|BLACKFRIDAY|BLOG|BLUE|BOUTIQUE|BROKER|BUILD|BUILDERS|BUSINESS|BUZZ|BZH|CAB|CAFE|CAM|CAMERA|CAMP|CAPITAL|CAR|CARDS|CARE|CAREER|CAREERS|CARS|CASA|CASH|CASINO|CAT|CATERING|CENTER|CHAT|CHEAP|CHRISTMAS|CHURCH|CITY|CLAIMS|CLEANING|CLICK|CLINIC|CLOTHING|CLOUD|CLUB|COACH|CODES|COFFEE|COLLEGE|COMMUNITY|COMPANY|COMPUTER|CONDOS|CONSTRUCTION|CONSULTING|CONTRACTORS|COOKING|COOL|COUNTRY|COUPONS|COURSES|CREDIT|CREDITCARD|CRICKET|CRUISES|DANCE|DATE|DATING|DEALS|DEGREE|DELIVERY|DEMOCRAT|DENTAL|DENTIST|DESI|DESIGN|DIAMONDS|DIET|DIGITAL|DIRECT|DIRECTORY|DISCOUNT|DOG|DOMAINS|DOWNLOAD|EARTH|ECO|EDUCATION|EMAIL|ENERGY|ENGINEER|ENGINEERING|ENTERPRISES|EQUIPMENT|ESTATE|EUS|EVENTS|EXCHANGE|EXNET\.SU|EXPERT|EXPOSED|EXPRESS|FAIL|FAITH|FAMILY|FANS|FARM|FASHION|FEEDBACK|FILM|FINANCE|FINANCIAL|FISH|FISHING|FIT|FITNESS|FLIGHTS|FLORIST|FLOWERS|FM|FOOTBALL|FOREX|FORSALE|FOUNDATION|FRL|FUN|FUND|FURNITURE|FUTBOL|FYI|GALLERY|GAME|GAMES|GARDEN|GENT|GIFT|GIFTS|GIVES|GLASS|GLOBAL|GMBH|GOLD|GOLF|GRAPHICS|GRATIS|GREEN|GRIPE|GROUP|GUIDE|GUITARS|GURU|HAUS|HEALTHCARE|HELP|HIPHOP|HIV|HOCKEY|HOLDINGS|HOLIDAY|HORSE|HOSPITAL|HOST|HOSTING|HOUSE|HOW|IMMO|IMMOBILIEN|INDUSTRIES|INK|INSTITUTE|INSURE|INTERNATIONAL|INVESTMENTS|JETZT|JEWELRY|JOBS|JUEGOS|KAUFEN|KIM|KITCHEN|KIWI|LAND|LAWYER|LEASE|LEGAL|LGBT|LIFE|LIGHTING|LIMITED|LIMO|LINK|LIVE|LOAN|LOANS|LOL|LOVE|LTD|LTDA|LUXURY|MAISON|MANAGEMENT|MARKET|MARKETING|MARKETS|MBA|MEDIA|MEMORIAL|MEN|MENU|MOBI|MODA|MOE|MOM|MONEY|MOVIE|NETWORK|NINJA|OBSERVER|ONE|ONL|ONLINE|OOO|PARTNERS|PARTS|PARTY|PET|PHOTO|PHOTOGRAPHY|PHOTOS|PHYSIO|PICS|PICTURES|PINK|PIZZA|PLACE|PLUMBING|PLUS|POKER|PORN|PRESS|PRO|PRODUCTIONS|PROMO|PROPERTIES|PROPERTY|PROTECTION|PUB|QPON|RADIO\.AM|RADIO\.FM|RACING|REALTY|RECIPES|RED|REHAB|REISEN|RENT|RENTALS|REPAIR|REPORT|REST|RESTAURANT|REVIEWS|RIP|ROCKS|RODEO|RUN|SALE|SALON|SARL|SCHOOL|SCHULE|SCIENCE|SECURITY|SERVICES|SEX|SEXY|SHIKSHA|SHOES|SHOP|SHOPPING|SHOW|SINGLES|SITE|SKI|SOCCER|SOCIAL|SOFTWARE|SOLAR|SOLUTIONS|SOY|SPACE|STORE|STREAM|STUDIO|STUDY|SUCKS|SUPPLIES|SUPPLY|SUPPORT|SURF|SURGERY|SYSTEMS|TATTOO|TAX|TAXI|TEAM|TECH|TECHNOLOGY|TEL|TENNIS|THEATER|THEATRE|TIENDA|TIPS|TIRES|TODAY|TOOLS|TOP|TOURS|TOWN|TOYS|TRADE|TRADING|TRAINING|TRAVEL|TUBE|TV|UNIVERSITY|UNO|VACATIONS|VENTURES|VET|VIAJES|VIDEO|VILLAS|VIN|VIP|VISION|VODKA|VOTE|VOTO|VOYAGE|WANG|WATCH|WEBCAM|WEBSITE|WEDDING|WHOSWHO|WIKI|WIN|WINE|WORK|WORKS|WORLD|WTF|XXX|XYZ|YOGA|ZONE|ART|BAR|COLLEGE|DESIGN|FEEDBACK|HOST|INK|LOVE|OBSERVER|ONLINE|PRESS|PROTECTION|RADIO\.AM|RADIO\.FM|REALTY|RENT|REST|SECURITY|SHOP|SITE|SPACE|STORE|TATTOO|TECH|TEL|THEATRE|TV|WEBSITE|WIKI|XYZ|EU|EU\.COM|AT|CO\.AT|OR\.AT|BE|CH|CZ|ES|COM\.ES|NOM\.ES|ORG\.ES|GB\.NET|GR\.COM|HU\.NET|IM|CO\.IM|COM\.IM|NET\.IM|ORG\.IM|LI|LT|LU|LV|ANS\.LV|COM\.LV|CONF\.LV|EDU\.LV|ID\.LV|NET\.LV|ORG\.LV|ME|NL|PL|COM\.PL|NET\.PL|ORG\.PL|INFO\.PL|BIZ\.PL|EDU\.PL|NOM\.PL|SHOP\.PL|WAW\.PL|SE\.NET|SI|SK|CO\.UK|ORG\.UK|ME\.UK|UK\.COM|UK\.NET|LONDON|GR|RO|COM\.RO|FI|DE|COM\.DE|DE\.COM|BERLIN|KOELN|COLOGNE|HAMBURG|WIEN|BAYERN|SCOT|BRUSSELS|VLAANDEREN|WALES|CYMRU|MELBOURNE|LAT|GENT|SAARLAND|IST|ISTANBUL|EU|EU\.COM|BE|GR|COM\.RO|BERLIN|ASIA|AE|AE\.ORG|AF|COM\.AF|NET\.AF|ORG\.AF|CN\.COM|CX|CHRISTMAS|IN|CO\.IN|NET\.IN|IN\.NET|ORG\.IN|GEN\.IN|FIRM\.IN|IND\.IN|IO|JP|JP\.NET|JPN\.COM|TOKYO|NAGOYA|YOKOHAMA|LA|MN|MY|COM\.MY|NET\.MY|ORG\.MY|PK|PH|COM\.PH|NET\.PH|ORG\.PH|QA|SA\.COM|TL|TW|COM\.TW|IDV\.TW|CLUB\.TW|EBIZ\.TW|GAME\.TW|TO|IST|ISTANBUL|IN\.NET|US|US\.COM|US\.ORG|LA|CO|AG|CO\.AG|COM\.AG|NET\.AG|ORG\.AG|NOM\.AG|BR\.COM|BZ|CO\.BZ|COM\.BZ|NET\.BZ|ORG\.BZ|QUEBEC|CL|COM\.CO|CO\.COM|NET\.CO|NOM\.CO|EC|COM\.EC|NET\.EC|INFO\.EC|PRO\.EC|MED\.EC|FIN\.EC|GL|CO\.GL|COM\.GL|NET\.GL|ORG\.GL|GS|GY|CO\.GY|COM\.GY|NET\.GY|HN|COM\.HN|NET\.HN|ORG\.HN|HT|COM\.HT|NET\.HT|ORG\.HT|INFO\.HT|LC|CO\.LC|COM\.LC|NET\.LC|ORG\.LC|MX|COM\.MX|MEX\.COM|PE|COM\.PE|NET\.PE|ORG\.PE|SR|SX|VC|COM\.VC|NET\.VC|ORG\.VC|CO\.VE|COM\.VE|VEGAS|NYC|MIAMI|BOSTON|US\.COM|US\.ORG|AC|AFRICA|AS|CC|CD|CM|CO\.CM|COM\.CM|NET\.CM|FM|RADIO\.FM|GG|KI|COM\.KI|NET\.KI|ORG\.KI|BIZ\.KI|INFO\.KI|JE|LY|COM\.LY|MS|MU|COM\.MU|NET\.MU|ORG\.MU|NF|COM\.NF|NET\.NF|ORG\.NF|NG|COM\.NG|NET\.NG|NU|NZ|CO\.NZ|NET\.NZ|ORG\.NZ|COM\.SB|NET\.SB|ORG\.SB|SC|COM\.SC|NET\.SC|ORG\.SC|SH|SO|ST|TK|WS|ZA\.COM|CO\.ZA|NET\.ZA|ORG\.ZA|WEB\.ZA|PS|NET\.SO|IRISH|ML|CF|MG|TV|FM|SRL|DURBAN|JOBURG|CAPETOWN|CC|RADIO\.FM|TV|UK)((\/|\?)[-а-яА-ЯёЁa-zA-Z0-9+&@#\/%?=~_|!:,.;]{0,2048})?)(\b|"|'|\s|$)/gimu,
			function(match, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15) {
				var title = '',
					isEmail = match.indexOf('@') !== -1,
					first = p1 === '//' ? '' : p1,
					second = p1 === '//' ? p1 + p6 : p6,
					url = (p6.indexOf('//') !== -1 ? '' : 'http://') + p6

                second = truncate(second, 30)
				if (isEmail) {
					return '<a href="mailto:' + match + '">' + match + '</a>'
				} else {

                    return first + '<a target="_blank" href="' + url + '">' + second + '</a>' + p15
				}
			}
		)
	}
	return wrapTextPartUrls(text)
	/*eslint-enable */
}

export default wrapTextUrls
